const users = [
    {
        _id: "1",
        username: "admin",
        name: "admin",
        password: "admin",
        profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
        gender: "male",
    },
    {
        _id: "2",
        username: "user",
        name: "user",
        password: "user",
        profilePicture: "https://randomuser.me/api/portraits/men/2.jpg",
        gender: "male",
    }, 
    {
        _id: "3",
        username: "user2",
        name: "user2",
        password: "user2",
        profilePicture: "https://randomuser.me/api/portraits/men/3.jpg",
        gender: "male",
    },
    {
        _id: "4",
        username: "user3",
        name: "user3",
        password: "user3",
        profilePicture: "https://randomuser.me/api/portraits/men/4.jpg",
        gender: "male",
    },
    {
        _id: "5",
        username: "user4",
        name: "user4",
        password: "user4",
        profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
        gender: "male",
    },
    {
        _id: "6",
        username: "user5",
        name: "user5",
        password: "user5",
        profilePicture: "https://randomuser.me/api/portraits/men/6.jpg",
        gender: "male",
    },
    {
        _id: "7",
        username: "user6",
        name: "user6",
        password: "user6",
        profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
        gender: "male", 
    },
    {
        _id: "8",
        username: "user7",
        name: "user7",
        password: "user7",  
        profilePicture: "https://randomuser.me/api/portraits/men/8.jpg",
        gender: "male",
    },
    {
        _id: "9",
        username: "user8",
        name: "user8",
        password: "user8",  
        profilePicture: "https://randomuser.me/api/portraits/men/9.jpg",    
        gender: "male", 
    },
    {
        _id: "10",
        username: "user9",
        name: "user9",
        password: "user9",  
        profilePicture: "https://randomuser.me/api/portraits/men/10.jpg",    
        gender: "male", 
    },
];